### PR TITLE
Add CFL framework

### PR DESCRIPTION
**Pull request by lucasgaspar**
Added CFL framework and Main game scene

https://github.com/amco/lagranlucha-client/issues/3

### CODE REVIEW

**Review by SrTartarus — APPROVED** [review]
:shipit:

**Review by anaisrmzl — COMMENTED** [review]
Is it necessary to add all plugins used in this project to the readme?

**Comment by Horothenic** [comment]
> Is it necessary to add all plugins used in this project to the readme?

If they are inside the CFL FMK only the FMK should be added.

**Review by anaisrmzl — APPROVED** [review]
:shipit:

**Pull request merged**
